# Generated by Django 4.0.6 on 2022-07-14 21:44

import auto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=200, unique=True)),
                ('production_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year])),
                ('vin', models.CharField(max_length=200, unique=True)),
                ('certificate_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year])),
                ('certificate_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
