# Generated by Django 4.0.6 on 2022-07-16 04:59

import auto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('plate_number', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\s]+$', message='Только заглавные латинские буквы и цифры')], verbose_name='Регистрационный номер')),
                ('production_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year], verbose_name='Год выпуска')),
                ('vin', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', message='Только заглавные латинские буквы и цифры')])),
                ('certificate_id', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[А-ЯA-Z0-9\\s№]+$')], verbose_name='Номер СТС (свидетельство о регистрации)')),
                ('certificate_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year], verbose_name='Дата СТС')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
