# Generated by Django 4.0.6 on 2022-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_plate_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Транспортное средство'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='certificate_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Номер СТС (свидетельство о регистрации)'),
        ),
    ]
