# Generated by Django 4.0.6 on 2022-07-14 22:01

import auto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_auto_options_alter_auto_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='certificate_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year], verbose_name='Дата СТС'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='manufacturer',
            field=models.CharField(max_length=200, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='production_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), auto.models.max_value_current_year], verbose_name='Год выпуска'),
        ),
    ]
