# Generated by Django 4.0.6 on 2022-07-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_auto_certificate_year_alter_auto_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
    ]
